### ISSUE TITLE
Dirk, Gunong, and Pugio

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#20]
These look cool.

![dirk](https://cloud.githubusercontent.com/assets/17688683/17824976/1ab187a8-6633-11e6-87df-35eb4f5c874f.png)
![gunong](https://cloud.githubusercontent.com/assets/17688683/17824982/2161b60e-6633-11e6-8de1-e19f90f90045.png)
![pugio](https://cloud.githubusercontent.com/assets/17688683/17824983/226963ee-6633-11e6-8a50-455f84ca8a97.png)

Must give stats.

**Comment by Amazinite** [comment]
The Stratofortress isn't used anywhere either.
![stratofortress](https://cloud.githubusercontent.com/assets/17688683/17825021/55a3a332-6633-11e6-8a2f-57fee182a5a9.png)

**Comment by FriendlyNeighbour** [comment]
I was planning on making that first ship mainly used as the Plenipotent Dominion's system-guard ships. They would spawn in a fleet that typically patrols their home systems. They would be sort of like the Republic's Frigate in terms of it's strength compared to the rest of the Alpha fleet.
The second ship I figured would be more covert ops (Like the Stiletto)
The third ship would be their cargo ship (since they currently don't have one.)

**Comment by Amazinite** [comment]
Sounds hot.

**Comment by Disiuze** [comment]
What about the Stratofortress?

**Comment by Amazinite** [comment]
closing this because it was moved to the project notes.
