### ISSUE TITLE
SU Korath Systems

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#27]
They need Korath stations within them.

**Comment by FriendlyNeighbour** [comment]
That is very true. Although there is one Korath system that is actually attached to Dominion space via hyperspace route, and I ideally don't want that to shout: "Herro! I am alien and dis is mi station!" because I know a lot of players that may be new to the game just decide to go the mod route before playing vanilla. (don't want to destroy that which MZ designed in a certain way, with the eastern systems and the Korath being kind of a secret unless you happen across them.)

**Comment by Amazinite** [comment]
550a525
