### ISSUE TITLE
That_Someone_Fixes file

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#5]
How does this file fix stuff from That Someone?
That Someone's Pug fleets are using ships that he did the stats for. The TS Fixes file set his fleets back to the vanilla Pug ships. Pretty sure this should be removed.

**Comment by FriendlyNeighbour** [comment]
Well I put that there due to how he has the only system Pug system he adds set up:
One pug system, two factions that constantly fight.
Player comes in, can just sit there, Pug kill each other, leaving some ships disabled.
Player just takes some OP outfits that are ridiculous.
However that file was added before the "self destruct" function, and the file that sets them to default Pug could be removed, and those Pug ships 100% chance of self destruct to eliminate chance of player getting those outfits.

**Comment by Amazinite** [comment]
e311b07
