### ISSUE TITLE
Alphas.txt

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#7]
Is there any reason that these guys all use Mil'taj outfits, or should I make them their own?
I'm eventually going to go through and rebalance all the folders one by one (if you want), or at the very least all human related outfits and ships, so I could make them their own stuff if you wanted.

**Comment by FriendlyNeighbour** [comment]
The idea is that the Alpha's were preserved by the Pug and were given a method of increasing their population (minus the whole kidnapping and impregnating women thing) meanwhile the Mil'taj supplied them with some weapons to help get revenge against the Quarg (since the Mil'taj didn't end up too well after that first go.)
