### ISSUE TITLE
Lots of outfits with no images

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#8]
Kind of obvious, but I think that's something we need to fix.

**Comment by Disiuze** [comment]
Another problem is a shitton of images that are duped.

**Comment by Amazinite** [comment]
That too.

**Comment by FriendlyNeighbour** [comment]
Unfortunately I'm not very good at that, and I feel like doing a google search and putting in something from there is kind of... lame. Someone gave a good idea that I did a couple times, which was recolour some stock sprites from vanilla. (That too seems kinda lame, but at least the style would fit with the actual game, since it's, you know, the game's.)

**Comment by Amazinite** [comment]
Yeah; that's what I did with much of my own mod, since I can't Blender for shit. I've still got to try and figure Blender out, so I'll probably do that after releasing v0.5.5 of my mod.

**Comment by Amazinite** [comment]
Could you create a list of outfits without images/with duplicate images the same way that there's the list of ships?

**Comment by Amazinite** [comment]
This has pretty much been moved to #35
