### ISSUE TITLE
Shorten some Phil ship names

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#97]
A lot of the long names tend to run into things when looking in the info panel. Stuff like Vanguard Trailbreaker or Fortress Protector could probably just be shortened to Trailbreaker and Fortress.

**Comment by Elyssaen** [comment]
Is Phil active these days? I use Phil's Flavours all the time, kind of consider it part of the main game at this point, but while so much of it is _amazing_, it does need a little bit of attention here and there. Namely:

1. I'm itching to rewrite some of the descriptions.
2. Some of the very long names, like The Screams of the Insane, are a bit of a problem. (More than Vanguard Trailbreaker, I think.)
3. Some of the ships are so well balanced that, well, there aren't that many I consider flying. The Katalox is great, though technically I always know I'm picking it because it's more balanced than the Bactrian. The X2 Gunship is great too. But there are some really pretty pirate-like ships that never really compete with options like the Blackbird, Osprey and Falcon, so I end up treating 95+% of his beautiful ships like background.

(Just noticed I'm using the very first version he posted on Google Groups. Might get the new one, though the Alliance Battleship seems like it might diverge from the balance a little... that ship... I mean, it's realistic for a T1.5 'super heavy', but it's a bit scary and might break the Uncapturable Wardragons balance.)

**Comment by Amazinite** [comment]
Vanguard Trailbreaker -> Trailbreaker
Fortress Protector -> Fortress
####X2 Armed Freight -> ####X2A Freight
####X2 Super Freighter > ####X2S Freight
4500X2 gunship -> 4500X2 Gunship (capitalization)
X2 Gunship (Engines) -> X2E Gunship
Remove "the" in any names
Screams of the Insane -> Insane Screams?
Lightning in the Storm -> Stormy Lightning?

**Comment by Elyssaen** [comment]
I'm up for most of those. The last two, though, are trickier. X of the Y has a really cool sound, it just is troublingly long and so doesn't really work in ES. But directly turning them into Y X loses a lot of the quality it had.

I think if X of the Y names don't work, you have to go a bit back to the drawing board. Screams of the Insane could do quite well as Hellscream. Similar connotation, especially for anybody who gets the reference. 

Lightning in the Storm... the connotation is of this bolt streaking through chaos. Stormy Lightning doesn't have it to me. Just Lightning should be a perfectly good name, but for this manufacturer seems too simple. By analog to Hellscream, perhaps Stormbolt.

**Comment by Amazinite** [comment]
4d201e4 I believe I got all the things mentioned here, but I might shorten a few more down. e.g. Damned Executioner to just Executioner. Leaving this open until I decide.

**Comment by Amazinite** [comment]
The rest seem good. I'm leaving them as is.
